### ISSUE TITLE
Text file containing all words in English

### ISSUE THREAD

**Issue by ndvbd** [freedict/libdict#13]
How can we use Freedict to get a simple list of all words in English?

**Comment by humenda** [comment]
You can learn about all our dictionaries using our
API: https://freedict.org/downloads/#api  
Such questions are better suited for our mailing list and IRC channel, please
see <https://freedict.org/community/>.  
We are looking forward to your message, meanwhile I close this issue here.

**Comment by ndvbd** [comment]
Maybe it's worth mentioning it in the comments. I'm looking for a simple file, not an API

**Comment by bansp** [comment]
I'm afraid you're stating your task rather imprecisely. "All words in English" is a rather unattainable goal, and pretty pointless as well. (Auxiliary questions: which English? "all" in what sense? what do you mean by "words"?)
A list of headwords (not "words") from a single dictionary that has English as the source can be obtained by trying an XPath statement such as `//orth`  (you may need to experiment depending on the dictionary). This is also pretty useless for general purposes, so **we don't create such dumps**.
Like Sebastian said, your problem is not an issue for the ticketing system, so please use the tips that Sebastian has provided if you wish to pursue this issue (but if you do, please prepare answers to the auxiliary questions above in advance). Thanks!
