### ISSUE TITLE
add relative seeking

### ISSUE THREAD

**Issue by humenda** [freedict/libdict#3]
Currently, each seek is performed from the start of the opened .dict file. It
would be better to save the current position (e.g. with a Cursor) and seek to
the next definition relatively.

**Comment by ghost** [comment]
Closed without fix.

Adding this features would, if at all, only provide a very minor performance increase in some situations (platform-dependent). On the other hand, it introduces a high risk of bugs occuring, because one would have to keep track of the current cursor position. It is difficult to guarantee that this is always correctly synced with the actual position, e.g. after an unsuccessful read operation.
